### ISSUE TITLE
Cannot add a match with Koen in it

### ISSUE THREAD

**Issue by agoblet** [BigDataRepublic/kickerscore#22]
Koens name is not shown in the user list when adding a match. This probably happens because he did not fill in his name on slack. It is not possible to add a match with Koen in it.

**Comment by bneijt** [comment]
Is the issue resolved if Koen adds his name to slack, has he tried?

**Comment by agoblet** [comment]
It works when you add a name to slack. Yet, we should add something to prevent these things from happening. 2 Options:
- Filter out users in the slack channel that do not have a name
- Make it possible for users without a name to be added to a match

**Comment by StevenReitsma** [comment]
Fixed in v2
